### ISSUE TITLE
theming

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/invenio-theme-tugraz#149]
**invenio-theme-tugraz**

This module is overriding some parts of the theme.
in order to have some default colors and use only these colors in the templates, we need to specify the colors first, and then decide on which color should be used where.

1.  **theme colors**
investigate the colors used overall in the templates.
and add them to this list/issue.

    ```#231f20``` - tugraz black
    ```#e4154b``` - tugraz red
    ```#777``` - grey
    ```#f2f2f2``` - footer background
    ```#000``` - font color
    ...

2. **badges colors**
investigate the colors used for badges.
    *for example- open access badge*
    ```css
    .ui.label.access-right.open {
        background-color: #21ba45;
    }
    ```

3. **Solve Themeing**
    * create variables for colors ```variables.less```
    *for example*
    ```@accessRightOpen: #e9711c;```

4. use variables to define the colors.
    *for example overriding open access badge.*
    ```css
    .ui.label.access-right.open {
      background-color: @accessRightOpen;
    } 
    ```
by opening this issue we are closing #76, #59 and #54 since they are identical.
